# Generated by Django 5.2.6 on 2025-10-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergiContent', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
