# Generated by Django 5.2.6 on 2025-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergiContent', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('Collections Partnership', 'Collections Partnership'), ('Technology Integration', 'Technology Integration'), ('Careers', 'Careers'), ('Other', 'Other')], max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Enquiry',
                'verbose_name_plural': 'Quick Enquiries',
            },
        ),
    ]
