# Generated by Django 5.2.6 on 2025-10-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergiContent', '0004_quickenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
