# Generated by Django 4.2.25 on 2025-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergiContent', '0005_resumesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('Data Breach / Security Incident', 'Data Breach / Security Incident'), ('Ethics / Misconduct', 'Ethics / Misconduct'), ('Harassment / Discrimination', 'Harassment / Discrimination'), ('Fraud / Financial Irregularity', 'Fraud / Financial Irregularity'), ('Other', 'Other')], max_length=100)),
                ('details', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='confidential_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(upload_to='cv_uploads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
